language: java

services:
    - docker

addons:
    sonarcloud:
        organization: "asc-lab"
        token:
            secure: $SONAR_TOKEN

script:
    - make
    - make docker-login
    - make TAG=${TRAVIS_BUILD_NUMBER} tag
    - make TAG=${TRAVIS_BUILD_NUMBER} push-tag
    - make push-latest
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install org.jacoco:jacoco-maven-plugin:report sonar:sonar

