server:
  port: ${SERVICE_PORT:9004}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PASS:admin}
      database: ${MONGO_DB:admin}
    elasticsearch:
      cluster-name: ${ELASTICSEARCH_CLUSTER:docker-cluster}
      cluster-nodes: ${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9300}

logging:
  level:
    org:
      springframework: DEBUG


security:
  oauth2:
    resource:
      id: accrual-rest-api
      jwt:
        key-value: secretKey

#axon:
#  eventhandling:
#    processors:
#      queryModel:
#        mode: tracking
#        source: eventBus

management:
  endpoint:
    health:
      show-details: always